databases:
  - name: rails_capston_database
    databaseName: rails_capston_database
    user: rails_capston_database_user

services:
  - type: web
    name: rails_capston_web_service
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails_capston_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false